spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://[Insert database endpoint URL here.] 
    username: [Insert database root username.]
    password: [Insert database root password.]
